apiVersion: v1
kind: Service
metadata:
  name: superadmin-backend
  namespace: backend
spec:
  type: NodePort
  selector:
    app: superadmin-backend
  ports:
    - port: 82
      targetPort: 85
      nodePort: 30005
      protocol: TCP


