services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    working_dir: /var/www/superadmin
    expose:
      - 9000
    networks:
      - agencis

  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/superadmin
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - agencis

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: superadmin
      MYSQL_USER: superadmin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/storage/data/mysql:/var/lib/mysql
    networks:
      - agencis


networks:
    agencis:
        name: agencis


