apiVersion: apps/v1
kind: Deployment
metadata:
  name: superadmin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superadmin-frontend
  template:
    metadata:
      labels:
        app: superadmin-frontend
    spec:
      imagePullSecrets:
        - name: secret-registry
      containers:
        - name: superadmin-frontend
          image: 834033184010.dkr.ecr.ap-southeast-2.amazonaws.com/superadmin-frontend:latest
          imagePullPolicy: Always