apiVersion: v1
kind: Service
metadata:
  name: superadmin-nginx-service
spec:
  selector:
    app: superadmin-nginx
  ports:
    - port: 80
      targetPort: 81
      protocol: TCP
  type: LoadBalancer